import { getRepoRoot } from "../util/paths.js";
import { loadTaskById } from "../core/task-store.js";
import { assertTaskOwnership } from "../core/session.js";
import { run } from "../util/exec.js";
import { createTaskEvent, appendTaskTranscript } from "../core/audit.js";
import { TaskNotFoundError } from "../core/errors.js";
import type { Task } from "../core/task.js";
import { logInfo, logHeader, logSuccess } from "../util/logging.js";

function requireTask(taskId: string): Task {
  const task = loadTaskById(taskId);
  if (!task) throw new TaskNotFoundError(taskId);
  return task;
}

export async function cmdDiff(taskId: string): Promise<void> {
  const repoRoot = getRepoRoot();
  const task = requireTask(taskId);

  if (!task.worktree) {
    throw new Error(`No worktree found for ${taskId}. Run 'taskforge start ${taskId}' first.`);
  }

  logHeader(`Diff: ${taskId}`);
  const result = await run("git", ["-C", task.worktree, "diff"], repoRoot);
  process.stdout.write(result.stdout);
}

export async function cmdCheckpoint(taskId: string, message: string): Promise<void> {
  const repoRoot = getRepoRoot();
  const task = requireTask(taskId);

  assertTaskOwnership(task, repoRoot);

  if (!task.worktree) {
    throw new Error(`No worktree found for ${taskId}.`);
  }

  const branchResult = await run("git", ["-C", task.worktree, "rev-parse", "--abbrev-ref", "HEAD"], repoRoot);
  const branch = branchResult.stdout.trim();

  if (branch === "main" || branch === "task-state") {
    throw new Error(`Refusing to checkpoint on ${branch} branch.`);
  }

  const fullMessage = [
    message,
    "",
    `Task: ${taskId}`,
    `TaskForge-Managed: true`,
  ].join("\n");

  await run("git", ["-C", task.worktree, "add", "."], repoRoot);
  await run("git", ["-C", task.worktree, "commit", "-m", fullMessage], repoRoot);

  logSuccess(`Checkpoint created for ${taskId}: ${message}`);

  appendTaskTranscript(repoRoot, taskId, createTaskEvent(taskId, "git.commit", {
    summary: message,
  }));
}

export async function cmdSubmit(taskId: string): Promise<void> {
  const repoRoot = getRepoRoot();
  const task = requireTask(taskId);

  assertTaskOwnership(task, repoRoot);

  if (!task.branch) {
    throw new Error(`No branch recorded for ${taskId}.`);
  }

  if (task.branch === "main" || task.branch === "task-state") {
    throw new Error(`Refusing to push ${task.branch}.`);
  }

  if (!task.worktree) {
    throw new Error(`No worktree found for ${taskId}.`);
  }

  logInfo(`Pushing branch: ${task.branch}`);

  await run("git", ["-C", task.worktree, "push", "origin", task.branch], repoRoot);

  logSuccess(`Branch ${task.branch} pushed for ${taskId}.`);

  appendTaskTranscript(repoRoot, taskId, createTaskEvent(taskId, "git.push", {
    summary: `Pushed branch ${task.branch}`,
  }));
}

export async function cmdPr(taskId: string): Promise<void> {
  const repoRoot = getRepoRoot();
  const task = requireTask(taskId);

  if (!task.branch) {
    throw new Error(`No branch recorded for ${taskId}.`);
  }

    logInfo(`Creating PR for ${taskId} from branch ${task.branch}...`);

  const title = `[${taskId}] ${taskId}`;

  const result = await run("gh", [
    "pr", "create",
    "--title", title,
    "--head", task.branch,
    "--base", "main",
    "--body", `Task: ${taskId}\n\nAuto-generated by TaskForge.`,
  ], repoRoot);

  logSuccess(`PR created for ${taskId}: ${result.stdout.trim()}`);
}
