import { getRepoRoot } from "../util/paths.js";
import { loadTaskById } from "../core/task-store.js";
import { assertTaskOwnership } from "../core/session.js";
import { run } from "../util/exec.js";
import { createTaskEvent, appendTaskTranscript } from "../core/audit.js";
import { TaskNotFoundError } from "../core/errors.js";
import { loadConfig } from "../core/config.js";
import { createPullRequest } from "../integrations/github/service.js";
import type { GitHubConfig } from "../integrations/github/types.js";
import type { Task } from "../core/task.js";
import { logInfo, logHeader, logSuccess, logWarn } from "../util/logging.js";

function requireTask(taskId: string): Task {
  const task = loadTaskById(taskId);
  if (!task) throw new TaskNotFoundError(taskId);
  return task;
}

export async function cmdDiff(taskId: string): Promise<void> {
  const repoRoot = getRepoRoot();
  const task = requireTask(taskId);

  if (!task.worktree) {
    throw new Error(`No worktree found for ${taskId}. Run 'taskforge start ${taskId}' first.`);
  }

  logHeader(`Diff: ${taskId}`);
  const result = await run("git", ["-C", task.worktree, "diff"], repoRoot);
  process.stdout.write(result.stdout);
}

export async function cmdCheckpoint(taskId: string, message: string): Promise<void> {
  const repoRoot = getRepoRoot();
  const task = requireTask(taskId);

  assertTaskOwnership(task, repoRoot);

  if (!task.worktree) {
    throw new Error(`No worktree found for ${taskId}.`);
  }

  const branchResult = await run("git", ["-C", task.worktree, "rev-parse", "--abbrev-ref", "HEAD"], repoRoot);
  const branch = branchResult.stdout.trim();

  if (branch === "main" || branch === "task-state") {
    throw new Error(`Refusing to checkpoint on ${branch} branch.`);
  }

  const fullMessage = [
    message,
    "",
    `Task: ${taskId}`,
    `TaskForge-Managed: true`,
  ].join("\n");

  await run("git", ["-C", task.worktree, "add", "."], repoRoot);
  await run("git", ["-C", task.worktree, "commit", "-m", fullMessage], repoRoot);

  logSuccess(`Checkpoint created for ${taskId}: ${message}`);

  appendTaskTranscript(repoRoot, taskId, createTaskEvent(taskId, "git.commit", {
    summary: message,
  }));
}

export async function cmdSubmit(taskId: string): Promise<void> {
  const repoRoot = getRepoRoot();
  const task = requireTask(taskId);

  assertTaskOwnership(task, repoRoot);

  if (!task.branch) {
    throw new Error(`No branch recorded for ${taskId}.`);
  }

  if (task.branch === "main" || task.branch === "task-state") {
    throw new Error(`Refusing to push ${task.branch}.`);
  }

  if (!task.worktree) {
    throw new Error(`No worktree found for ${taskId}.`);
  }

  logInfo(`Pushing branch: ${task.branch}`);

  await run("git", ["-C", task.worktree, "push", "origin", task.branch], repoRoot);

  logSuccess(`Branch ${task.branch} pushed for ${taskId}.`);

  appendTaskTranscript(repoRoot, taskId, createTaskEvent(taskId, "git.push", {
    summary: `Pushed branch ${task.branch}`,
  }));
}

export async function cmdPr(taskId: string): Promise<void> {
  const repoRoot = getRepoRoot();
  const task = requireTask(taskId);
  const config = loadConfig(repoRoot);

  if (!task.branch) {
    throw new Error(`No branch recorded for ${taskId}.`);
  }

  const title = `[${taskId}] ${taskId}`;
  const body = `Task: ${taskId}\n\nAuto-generated by TaskForge.`;

  if (config.github?.enabled && config.github.owner && config.github.repo) {
    logInfo(`Creating PR for ${taskId} from branch ${task.branch} via GitHub API...`);

    try {
      const githubConfig: GitHubConfig = {
        owner: config.github.owner,
        repo: config.github.repo,
        token: process.env.GITHUB_TOKEN,
      };
      const pr = await createPullRequest(githubConfig, title, task.branch, "main", body);

      logSuccess(`PR created for ${taskId}: #${pr.number} ${pr.url}`);

      appendTaskTranscript(repoRoot, taskId, createTaskEvent(taskId, "github.pr.created", {
        summary: `Created PR #${pr.number}`,
        metadata: { prNumber: pr.number, prUrl: pr.url },
      }));
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      logWarn(`PR creation failed for ${taskId}: ${message}`);

      appendTaskTranscript(repoRoot, taskId, createTaskEvent(taskId, "github.pr.failed", {
        summary: `PR creation failed: ${message}`,
      }));

      throw error;
    }
  } else {
    logWarn(`GitHub integration not configured. Manual PR creation required.`);
    logInfo(`To create a PR manually:`);
    logInfo(`  gh pr create --title "${title}" --head ${task.branch} --base main --body "${body}"`);
    logInfo(`  Or visit: https://github.com/<owner>/<repo>/compare/main...${task.branch}`);

    appendTaskTranscript(repoRoot, taskId, createTaskEvent(taskId, "github.pr.manual", {
      summary: "Manual PR creation required - GitHub not configured",
    }));
  }
}
