import fs from "node:fs";
import path from "node:path";
import { run } from "../util/exec.js";
import {
  readGateStamp,
  verifyGateStamp,
  type GateStamp,
} from "./gate-stamp.js";
import { parseSessionIdFromBranch } from "./session.js";
import { loadTaskById } from "./task-store.js";

/**
 * TypeScript implementations of the git hook checks (the enforcement boundary).
 * The hidden `taskforge _hook <name>` command dispatches to these, and the
 * generated bash hooks delegate to `_hook` (see hooks.ts).
 */

export interface HookResult {
  ok: boolean;
  reasons: string[];
}

export interface PushRef {
  local_ref: string;
  local_sha: string;
  remote_ref: string;
  remote_sha: string;
}

const ZERO_SHA = "0".repeat(40);

/** Default gate names a stamp must record as passed. */
const DEFAULT_EXPECTED_GATES = ["typecheck", "lint", "build", "test"];

function bypassed(envKeys: string[]): boolean {
  return envKeys.some((k) => !!process.env[k]);
}

async function stagedFiles(repoRoot: string): Promise<string[]> {
  const r = await run("git", ["diff", "--cached", "--name-only"], repoRoot);
  return r.stdout
    .split("\n")
    .map((s) => s.trim())
    .filter(Boolean);
}

async function currentBranch(repoRoot: string): Promise<string> {
  const r = await run("git", ["rev-parse", "--abbrev-ref", "HEAD"], repoRoot);
  return r.stdout.trim();
}

/** True when the working dir appears to be an agent-managed worktree. */
function inAgentWorktree(repoRoot: string): boolean {
  return fs.existsSync(path.join(repoRoot, "..", "worktrees"));
}

function taskIdFromBranch(branch: string): string | null {
  const m = branch.match(/(TASK-\d+)/);
  return m ? m[1] : null;
}

/**
 * Pre-commit logic. Blocks: commits on task-state, commits to main from agent
 * worktrees, staged edits to legacy tasks/*.md, staged edits to .git/, and
 * staged edits to .taskforge/gate-stamp.json (prevents forging gate evidence).
 */
export async function runPreCommitLogic(repoRoot: string): Promise<HookResult> {
  if (bypassed(["TASKFORGE_INTERNAL", "TASKFORGE_DOCTOR"])) {
    return { ok: true, reasons: [] };
  }

  const reasons: string[] = [];
  const branch = await currentBranch(repoRoot);

  if (branch === "task-state") {
    reasons.push(
      "Direct commits to task-state are forbidden. Use TaskForge CLI commands.",
    );
  }

  if (branch === "main" && inAgentWorktree(repoRoot)) {
    reasons.push(
      "Direct commits to main from an agent-managed worktree are forbidden.",
    );
  }

  const staged = await stagedFiles(repoRoot);

  if (staged.some((f) => /^tasks\/.*\.md$/.test(f))) {
    reasons.push(
      "Direct edits to tasks/*.md are forbidden. Task files live on the task-state branch.",
    );
  }
  if (staged.some((f) => f.startsWith(".git/"))) {
    reasons.push("Direct edits to .git/ are forbidden.");
  }
  if (staged.some((f) => f === ".taskforge/gate-stamp.json")) {
    reasons.push(
      "Direct edits to .taskforge/gate-stamp.json are forbidden (gate evidence is generated by 'taskforge gates').",
    );
  }

  return { ok: reasons.length === 0, reasons };
}

export interface PrePushOptions {
  /** Gate names the stamp must record as passed. Default: typecheck/lint/build/test. */
  expectedGates?: string[];
  /** Non-task branches permitted to push. Default: none. */
  allowedBranches?: string[];
  /** Lookup a task's assignee by id. Default: loadTaskById(taskId, repoRoot)?.assignee. */
  loadAssignee?: (taskId: string) => string | null | undefined;
  /** Read the gate stamp. Default: readGateStamp(repoRoot). */
  readStamp?: () => GateStamp | null;
}

/**
 * Pre-push logic — the enforcement boundary. Per ref:
 *  1. Protected-branch guard: block push to main/master/task-state.
 *  2. Force-push guard: block non-fast-forward updates.
 *  3. For task branches (agent/*): gate-stamp check (stamp.commit_sha == pushed
 *     sha, all expected gates passed) + branch-ownership check (branch's encoded
 *     session == task.assignee; prevents pushing an abandoned session's branch).
 *  4. Non-task branches: blocked unless in push.allowedBranches.
 */
export async function runPrePushLogic(
  repoRoot: string,
  refs: PushRef[],
  options: PrePushOptions = {},
): Promise<HookResult> {
  if (bypassed(["TASKFORGE_INTERNAL"])) {
    return { ok: true, reasons: [] };
  }

  const expectedGates = options.expectedGates ?? DEFAULT_EXPECTED_GATES;
  const allowedBranches = options.allowedBranches ?? [];
  const loadAssignee =
    options.loadAssignee ??
    ((taskId: string) => {
      try {
        return loadTaskById(taskId, repoRoot)?.assignee ?? null;
      } catch {
        return null;
      }
    });
  const readStamp = options.readStamp ?? (() => readGateStamp(repoRoot));

  const reasons: string[] = [];

  for (const ref of refs) {
    // 1. Protected-branch guard
    if (
      ref.remote_ref === "refs/heads/main" ||
      ref.remote_ref === "refs/heads/master"
    ) {
      reasons.push(
        "Pushing to main/master is forbidden for agents. Use pull requests.",
      );
    }
    if (ref.remote_ref === "refs/heads/task-state") {
      reasons.push(
        "Pushing to task-state is forbidden for agents. Use TaskForge CLI commands.",
      );
    }

    // 2. Force-push (non-fast-forward) detection. Branch creation (local zero)
    //    and new remote branch (remote zero) are allowed; overwriting is not.
    if (
      ref.local_sha !== ZERO_SHA &&
      ref.remote_sha !== ZERO_SHA &&
      ref.remote_sha !== ""
    ) {
      const baseR = await run(
        "git",
        ["merge-base", ref.local_sha, ref.remote_sha],
        repoRoot,
      );
      const base = baseR.stdout.trim();
      if (baseR.exitCode !== 0 || base !== ref.remote_sha) {
        reasons.push("Force push (non-fast-forward) is forbidden.");
      }
    }

    const branch = ref.local_ref.replace(/^refs\/heads\//, "");
    const isTaskBranch =
      branch.startsWith("agent/") || /TASK-\d+/.test(branch);

    if (isTaskBranch) {
      // 3a. Gate-stamp check
      const stamp = readStamp();
      const verify = verifyGateStamp(stamp, ref.local_sha, expectedGates);
      if (!verify.valid) reasons.push(...verify.reasons);

      // 3b. Branch-ownership check
      const branchSession = parseSessionIdFromBranch(branch);
      const taskId = taskIdFromBranch(branch);
      if (taskId && branchSession) {
        const assignee = loadAssignee(taskId);
        if (assignee && assignee !== branchSession) {
          reasons.push(
            `Branch '${branch}' belongs to session '${branchSession}' but task ${taskId} is assigned to '${assignee}'. Re-claim the task or use the current session's branch.`,
          );
        }
      }
    } else if (!allowedBranches.includes(branch)) {
      // 4. Non-task branch not explicitly permitted
      reasons.push(
        `Pushing non-task branch '${branch}' is not permitted. Only agent/* task branches may push (or add the branch to push.allowedBranches).`,
      );
    }
  }

  return { ok: reasons.length === 0, reasons };
}
