import fs from "node:fs";
import path from "node:path";
import { run } from "../util/exec.js";

/**
 * TypeScript implementations of the git hook checks. These mirror the bash
 * hooks generated by `hooks.ts` but live in testable TS so the pre-push
 * enforcement (gate-stamp + ownership, TF-SLIM-03) can be added here without
 * shell scripting.
 *
 * The hidden `taskforge _hook <name>` command (commands/hook.ts) dispatches to
 * these functions. The generated bash hooks may delegate to `_hook` in a later
 * task; for now both paths enforce the same rules.
 */

export interface HookResult {
  ok: boolean;
  reasons: string[];
}

export interface PushRef {
  local_ref: string;
  local_sha: string;
  remote_ref: string;
  remote_sha: string;
}

const ZERO_SHA = "0".repeat(40);

function bypassed(envKeys: string[]): boolean {
  return envKeys.some((k) => !!process.env[k]);
}

async function stagedFiles(repoRoot: string): Promise<string[]> {
  const r = await run("git", ["diff", "--cached", "--name-only"], repoRoot);
  return r.stdout
    .split("\n")
    .map((s) => s.trim())
    .filter(Boolean);
}

async function currentBranch(repoRoot: string): Promise<string> {
  const r = await run("git", ["rev-parse", "--abbrev-ref", "HEAD"], repoRoot);
  return r.stdout.trim();
}

/** True when the working dir appears to be an agent-managed worktree. */
function inAgentWorktree(repoRoot: string): boolean {
  // The main checkout co-located with worktrees has a sibling ../worktrees dir.
  return fs.existsSync(path.join(repoRoot, "..", "worktrees"));
}

/**
 * Pre-commit logic. Blocks: commits on task-state, commits to main from agent
 * worktrees, staged edits to legacy tasks/*.md, staged edits to .git/, and
 * staged edits to .taskforge/gate-stamp.json (prevents forging gate evidence).
 */
export async function runPreCommitLogic(repoRoot: string): Promise<HookResult> {
  if (bypassed(["TASKFORGE_INTERNAL", "TASKFORGE_DOCTOR"])) {
    return { ok: true, reasons: [] };
  }

  const reasons: string[] = [];
  const branch = await currentBranch(repoRoot);

  if (branch === "task-state") {
    reasons.push(
      "Direct commits to task-state are forbidden. Use TaskForge CLI commands.",
    );
  }

  if (branch === "main" && inAgentWorktree(repoRoot)) {
    reasons.push(
      "Direct commits to main from an agent-managed worktree are forbidden.",
    );
  }

  const staged = await stagedFiles(repoRoot);

  if (staged.some((f) => /^tasks\/.*\.md$/.test(f))) {
    reasons.push(
      "Direct edits to tasks/*.md are forbidden. Task files live on the task-state branch.",
    );
  }
  if (staged.some((f) => f.startsWith(".git/"))) {
    reasons.push("Direct edits to .git/ are forbidden.");
  }
  if (staged.some((f) => f === ".taskforge/gate-stamp.json")) {
    reasons.push(
      "Direct edits to .taskforge/gate-stamp.json are forbidden (gate evidence is generated by 'taskforge gates').",
    );
  }

  return { ok: reasons.length === 0, reasons };
}

/**
 * Pre-push logic (protected-branch guard). Blocks pushes to main/master and
 * task-state, and blocks non-fast-forward (force) updates to existing remote
 * branches. Gate-stamp + branch-ownership checks are added in TF-SLIM-03.
 */
export async function runPrePushLogic(
  repoRoot: string,
  refs: PushRef[],
): Promise<HookResult> {
  if (bypassed(["TASKFORGE_INTERNAL"])) {
    return { ok: true, reasons: [] };
  }

  const reasons: string[] = [];

  for (const ref of refs) {
    if (
      ref.remote_ref === "refs/heads/main" ||
      ref.remote_ref === "refs/heads/master"
    ) {
      reasons.push(
        "Pushing to main/master is forbidden for agents. Use pull requests.",
      );
    }
    if (ref.remote_ref === "refs/heads/task-state") {
      reasons.push(
        "Pushing to task-state is forbidden for agents. Use TaskForge CLI commands.",
      );
    }

    // Force-push (non-fast-forward) detection. Branch creation (local zero) and
    // new remote branch (remote zero) are allowed; overwriting existing refs is not.
    if (
      ref.local_sha !== ZERO_SHA &&
      ref.remote_sha !== ZERO_SHA &&
      ref.remote_sha !== ""
    ) {
      const baseR = await run(
        "git",
        ["merge-base", ref.local_sha, ref.remote_sha],
        repoRoot,
      );
      const base = baseR.stdout.trim();
      if (baseR.exitCode !== 0 || base !== ref.remote_sha) {
        reasons.push("Force push (non-fast-forward) is forbidden.");
      }
    }
  }

  return { ok: reasons.length === 0, reasons };
}
