import fs from "node:fs";
import path from "node:path";
import { run } from "../util/exec.js";
import { logInfo, logSuccess } from "../util/logging.js";
import { isExecutable } from "../core/templates.js";

const HOOKS_DIR = ".taskforge/hooks";

export interface HookInstallOptions {
  projectRoot: string;
  dryRun: boolean;
  installHooks: boolean;
}

export function installGitHooks(options: HookInstallOptions): void {
  const { projectRoot, dryRun, installHooks } = options;
  const hooksDir = path.join(projectRoot, HOOKS_DIR);

  if (!installHooks) {
    logInfo("Git hooks installation skipped (installHooks: false).");
    return;
  }

  if (dryRun) {
    logInfo("Git hooks would be installed:");
    logInfo(`  .taskforge/hooks/pre-commit`);
    logInfo(`  .taskforge/hooks/pre-push`);
    logInfo(`  .taskforge/hooks/post-commit`);
    logInfo(`  git config core.hooksPath .taskforge/hooks`);
    return;
  }

  if (!fs.existsSync(hooksDir)) {
    fs.mkdirSync(hooksDir, { recursive: true });
  }

  fs.writeFileSync(path.join(hooksDir, "pre-commit"), generatePreCommitHook(), { mode: 0o755 });
  fs.writeFileSync(path.join(hooksDir, "pre-push"), generatePrePushHook(), { mode: 0o755 });
  fs.writeFileSync(path.join(hooksDir, "post-commit"), generatePostCommitHook(), { mode: 0o755 });

  setHooksPath(projectRoot);

  logSuccess("Git hooks installed: .taskforge/hooks/pre-commit, pre-push, post-commit");
  logInfo("Set git config core.hooksPath to .taskforge/hooks");
}

export async function setHooksPath(projectRoot: string): Promise<void> {
  await run("git", ["config", "core.hooksPath", HOOKS_DIR], projectRoot);
}

export function checkHooks(projectRoot: string): { ok: boolean; issues: string[] } {
  const issues: string[] = [];
  const hooksDir = path.join(projectRoot, HOOKS_DIR);

  const requiredHooks = ["pre-commit", "pre-push", "post-commit"];
  for (const hook of requiredHooks) {
    const hookPath = path.join(hooksDir, hook);
    if (!fs.existsSync(hookPath)) {
      issues.push(`Missing hook: .taskforge/hooks/${hook}`);
    } else if (!isExecutable(hookPath)) {
      issues.push(`Hook not executable: .taskforge/hooks/${hook}`);
    }
  }

  return { ok: issues.length === 0, issues };
}

function generatePreCommitHook(): string {
  return `#!/usr/bin/env bash
# TaskForge managed pre-commit hook
# Do not edit directly — managed by taskforge init

set -euo pipefail

# Allow TaskForge internal operations
if [[ -n "\${TASKFORGE_INTERNAL:-}" ]] || [[ -n "\${TASKFORGE_DOCTOR:-}" ]]; then
  exit 0
fi

branch=\$(git rev-parse --abbrev-ref HEAD)

# Block commits on task-state unless internal
if [[ "\$branch" == "task-state" ]]; then
  echo "ERROR: Direct commits to task-state are forbidden."
  echo "Use TaskForge CLI commands to modify task state."
  exit 1
fi

# Block commits on main from agent worktrees
if [[ "\$branch" == "main" && -d "../worktrees" ]]; then
  echo "ERROR: Direct commits to main from agent-managed worktree are forbidden."
  exit 1
fi

# Block staged changes to legacy tasks directory
if git diff --cached --name-only | grep -q "^tasks/.*\\.md$"; then
  echo "ERROR: Direct edits to tasks/*.md are forbidden."
  echo "Task files live on the task-state branch."
  exit 1
fi

# Block staged changes to .git paths
if git diff --cached --name-only | grep -q "^\\.git/"; then
  echo "ERROR: Direct edits to .git/ are forbidden."
  exit 1
fi

# Block staged changes to gate-stamp.json (prevents forging gate evidence)
if git diff --cached --name-only | grep -q "^\\.taskforge/gate-stamp\\.json$"; then
  echo "ERROR: Direct edits to .taskforge/gate-stamp.json are forbidden."
  echo "Gate evidence is generated by 'taskforge gates' and must not be hand-edited."
  exit 1
fi

exit 0
`;
}

function generatePrePushHook(): string {
  return `#!/usr/bin/env bash
# TaskForge managed pre-push hook
# Do not edit directly — managed by taskforge init

set -euo pipefail

# Allow TaskForge internal operations
if [[ -n "\${TASKFORGE_INTERNAL:-}" ]]; then
  exit 0
fi

remote="\$1"
url="\$2"

# Block push to main from agent context
while read -r local_ref local_sha remote_ref remote_sha; do
  if [[ "\$remote_ref" == "refs/heads/main" ]]; then
    echo "ERROR: Pushing to main is forbidden for agents."
    echo "Use pull requests or TaskForge facade commands."
    exit 1
  fi

  # Block push to task-state unless internal
  if [[ "\$remote_ref" == "refs/heads/task-state" ]]; then
    echo "ERROR: Pushing to task-state is forbidden for agents."
    echo "Use TaskForge CLI commands to modify task state."
    exit 1
  fi

  # Block force push. Deleting a branch and creating a new remote branch are
  # allowed; non-fast-forward updates to existing branches are not.
  if [[ "\$local_sha" == "0000000000000000000000000000000000000000" ]]; then
    :
  elif [[ "\$remote_sha" == "0000000000000000000000000000000000000000" ]]; then
    :
  elif [[ -z "\$remote_sha" ]]; then
    :
  else
    base=\$(git merge-base "\$local_sha" "\$remote_sha" 2>/dev/null || true)
    if [[ "\$base" != "\$remote_sha" ]]; then
      echo "ERROR: Force push is forbidden."
      exit 1
    fi
  fi
done

exit 0
`;
}

function generatePostCommitHook(): string {
  return `#!/usr/bin/env bash
# TaskForge managed post-commit hook
# Do not edit directly — managed by taskforge init

set -euo pipefail

commit_hash=\$(git rev-parse HEAD)
branch=\$(git rev-parse --abbrev-ref HEAD)
author=\$(git log -1 --format='%an')
timestamp=\$(date -u +"%Y-%m-%dT%H:%M:%SZ")
message=\$(git log -1 --format='%s')

audit_dir=".taskforge/runtime/logs/taskforge/audit"
mkdir -p "\$audit_dir"

cat >> "\$audit_dir/git.jsonl" <<EOF
{"timestamp":"\$timestamp","event":"git.commit","branch":"\$branch","commit":"\$commit_hash","author":"\$author","message":"\$message"}
EOF

exit 0
`;
}
